CREATE TABLE users (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR2(50) UNIQUE NOT NULL,
    password VARCHAR2(255) NOT NULL,
    role VARCHAR2(20) CHECK (role IN ('admin', 'student')),
    PRIMARY KEY (user_id)
);

CREATE TABLE books (
    book_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR2(100),
    author VARCHAR2(100),
    available NUMBER(1) DEFAULT 1,
    PRIMARY KEY (book_id)
);

CREATE TABLE borrow_records (
    record_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    user_id NUMBER,
    book_id NUMBER,
    borrow_date DATE DEFAULT SYSDATE,
    return_date DATE,
    PRIMARY KEY (record_id),
    FOREIGN KEY (user_id) REFERENCES users(user_id),
    FOREIGN KEY (book_id) REFERENCES books(book_id)
);

INSERT INTO users (username, password, role) VALUES ('admin', 'admin123', 'admin');

INSERT INTO users (username, password, role) VALUES ('student1', 'student123', 'student');

INSERT INTO books (title, author) VALUES ('Data Structures', 'Mark Allen Weiss');
INSERT INTO books (title, author) VALUES ('Operating Systems', 'Silberschatz');

SELECT * FROM users;

SELECT *
FROM users
WHERE LOWER(username) = 'admin'
AND password = 'admin123';

SELECT * FROM users WHERE username = 'admin' AND password = 'admin123';

DELETE FROM users WHERE username = 'admin';

INSERT INTO users (username, password, role)
VALUES ('admin', 'adminb', 'admin');

COMMIT;

SELECT * FROM books;

SELECT * FROM borrow_records;

DELETE FROM books WHERE book_id = 1

COMMIT;

SELECT * FROM users;
INSERT INTO users (username, password, role) VALUES ('student2', 'student222', 'student');

SELECT * FROM books;

SELECT * FROM borrow_records;
COMMIT;
